require 'test/tc_queue'
require 'test/tc_besteffort_delivery'
require 'test/tc_reliable_delivery'
require 'test/tc_multicast'
require 'test/tc_kvs'
#require 'test/tc_metered_kvs'
require 'test/tc_disorderly_cart'
#require 'test/tc_destructive_cart'
